apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-configmap
  namespace: project
data:
  TODO_BACKEND_URL: http://todo-backend-app-service:2346
  PICSUM_URL: https://picsum.photos/1200
  IMAGE_PATH: /usr/src/app/files/image.jpg
  FRESH_TIMER: "600"