apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: lsxol/todo-app:latest
          env:
            - name: TODO_BACKEND_URL
              value: http://todo-backend-app-service:2346
          volumeMounts:
            - name: todo-volume
              mountPath: /usr/src/app/files
      volumes:
        - name: todo-volume
          persistentVolumeClaim:
            claimName: todo-pvc