apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: ping-pong-healthcheck-policy
  namespace: exercises
spec:
  default:
    config:
      httpHealthCheck:
        requestPath: /count
      type: HTTP
  targetRef:
    group: ""
    kind: Service
    name: ping-pong-service