quarkus.http.port = ${PORT:8080}

%dev.todo.backend.url=http://localhost:2346
%dev.picsum.url=https://picsum.photos/1200
%dev.image.path=/tmp/image.jpg
%dev.fresh.timer=600

%test.todo.backend.url=http://localhost:2346
%test.picsum.url=https://picsum.photos/1200
%test.image.path=/tmp/image.jpg
%test.fresh.timer=600