apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: exercises
  name: my-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: my-pv-volume
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
