quarkus.http.port=${PORT:8080}

quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://${POSTGRES_HOST}:5432/postgres
%prod.quarkus.datasource.username=postgres
%prod.quarkus.datasource.password=${POSTGRES_PASSWORD}

quarkus.liquibase.migrate-at-start=true

quarkus.liquibase.change-log=db/changeLog.sql

